FROM python:3.12-alpine
WORKDIR /app
RUN apk add --no-cache curl
COPY requirements-runtime.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
